apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge
  namespace: production
spec:
  selector:
    matchLabels:
      app: challenge
  template:
    metadata:
      labels:
        app: challenge
    spec:
      containers:
      - name: challenge
        image: prfagun1/challenge:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: MY_SECRET
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: my-secret
